#!/bin/bash

create_revision_cmd=(uv run alembic revision --autogenerate -m 'autogenerated migration')

echo "Creating Alembic revision, command:"
echo "  ${create_revision_cmd[*]}"

"${create_revision_cmd[@]}"
if [[ $? -ne 0 ]]; then
    echo "[ERROR] Failed creating database revision"
    exit $?
fi

echo ""
echo "Database revision created."
