tz = "Etc/UTC"

[logging]
log_level = "INFO"

[http]
http_cache_type = "sqlite"
http_cache_file_dir = ".cache/http/hishel"
http_cache_db_file = ".cache/http/hishel.sqlite3"
http_cache_check_ttl_every = 60

[database]
## SQLite
# db_type = "sqlite"
# db_drivername = "sqlite+pysqlite"
# db_username = ""
# # Set in .secrets.toml
# # db_password = ""
# db_host = ""
# db_port = ""
# db_database = ".db/db.dev.sqlite3"
# db_echo = true

## Postgres
db_type = "postgres"
db_drivername = "postgresql+psycopg2"
db_username = "postgres"
# Set in .secrets.toml
# db_password = ""
db_host = "localhost"
db_port = "5432"
db_database = "theweather-dev"
db_echo = true

## MySQL
# db_type = "mysql"
# db_drivername = "mysql+pymysql"
# db_username = "mysql"
# db_host = "localhost"
# db_port = 3306
# db_database = "theweather-dev"
