---
volumes:
  pgbackweb_data: {}

services:
  pgbackweb:
    image: eduardolat/pgbackweb:latest
    container_name: ${PGBACKWEB_CONTAINER_NAME:-pgbackweb}
    ports:
      - ${PGBACKWEB_WEBUI_PORT:-8085}:8085
    volumes:
      ## If you only use S3 destinations, you don't need this volume
      - ${PGBACKWEB_BACKUPS_DIR:-pgbackweb_data}:/backups
    environment:
      ## Generate with generate_pgbackweb_encryption_key.sh
      PBW_ENCRYPTION_KEY: ${PGBACKWEB_ENCRYPTION_KEY}
      PBW_POSTGRES_CONN_STRING: ${PGBACKWEB_PG_CONNECTION_STRING}
      TZ: ${TZ:-Etc/UTC}
