---
volumes:
  pgadmin_data: {}

networks:
  pg_net: {}

services:

  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_IMAGE_TAG:-latest}
    container_name: ${PGADMIN_CONTAINER_NAME:-pgadmin}
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - ${PGADMIN_PORT:-15432}:80
    volumes:
      - ${PGADMIN_DATA_DIR:-pgadmin_data}:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - pg_net

  postgres:
    networks:
      - pg_net

