---
volumes:
  redis_data: {}

networks:
  theweather_api_net: {}

services:
  redis:
    image: redis
    container_name: ${REDIS_CONTAINER_NAME:-redis}
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel verbose
    volumes:
      - ${REDIS_CACHE_DIR:-redis_data}:/data
    expose:
      - 6379
    ports:
      - ${REDIS_PORT:-6379}:6379
    networks:
      - theweather_api_net
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  api-server:
    networks:
      - theweather_api_net
