---
volumes:
  weatherapi_collector_logs: {}
  weatherapi_collector_db: {}

services:
  weatherapi-collector:
    restart: unless-stopped
    build:
      ## Set context to repo root
      context: ../..
      dockerfile: containers/weatherapi-collector/Dockerfile
      args:
        UV_BASE: ${UV_IMAGE_VER:-0.6.14}
        PYTHON_BASE: ${PYTHON_IMG_VER:-3.12-slim}
    working_dir: /app/collectors/weatherapi-collector
    container_name: weatherapi-collector
    command: ["uv", "run", "weatherapi-collector"]
    environment:
      TZ: ${TZ:-Etc/UTC}

      DYNACONF_LOGGING__LOG_LEVEL: ${WEATHERAPI_COLLECTOR_LOG_LEVEL:-INFO}
      DYNACONF_LOGGING__LOG_FILE_PATH: ${WEATHERAPI_COLLECTOR_LOG_FILE_PATH:-/var/log/weatherapi-collector/app.log}

      DYNACONF_HTTP__USE_CACHE: ${WEATHERAPI_COLLECTOR_USE_HTTP_CACHE:-false}
      DYNACONF_HTTP__CACHE_TYPE: ${WEATHERAPI_COLLECTOR_HTTP_CACHE_TYPE:-sqlite}
      DYNACONF_HTTP__CACHE_FILE_DIR: ${WEATHERAPI_COLLECTOR_HTTP_CACHE_DIR:-/app/.cache/http/hishel}
      DYNACONF_HTTP__CACHE_DB_FILE: ${WEATHERAPI_COLLECTOR_HTTP_CACHE_DB_FILE:-/app/.cache/weatherapi-collector/http/hishel.sqlite3}
      DYNACONF_HTTP__CACHE_CHECK_TTL_EVERY: ${WEATHERAPI_COLLECTOR_HTTP_CACHE_CHECK_TTL_EVERY:-60}
      DYNACONF_HTTP__CACHE_TTL: ${WEATHERAPI_COLLECTOR_HTTP_CACHE_TTL:-300}

      DYNACONF_WEATHERAPI__APSCHEDULER__REQUEST_JOBS_SCHEDULE: ${WEATHERAPI_APSCHEDULER_REQUEST_JOBS_SCHEDULE:-"*/15 * * * *"}
      DYNACONF_WEATHERAPI__APSCHEDULER__DATA_JOBS_SCHEDULE: ${WEATHERAPI_APSCHEDULER_DATA_JOBS_SCHEDULE:-"*/20 * * * *"}
      DYNACONF_WEATHERAPI__APSCHEDULER__CLEANUP_JOBS_SCHEDULE: ${WEATHERAPI_APSCHEDULER_CLEANUP_JOBS_SCHEDULE:-"*/5 * * * *"}

      DYNACONF_WEATHERAPI__API_KEY: ${WEATHERAPI_KEY}
      DYNACONF_API_SERVER__BASE_URL: ${API_SERVER_BASE_URL:-http://api-server:8000}
      DYNACONF_WEATHERAPI__LOCATION_NAME: ${WEATHERAPI_LOCATION_NAME}
      DYNACONF_WEATHERAPI__RUN_SCHEDULER: ${WEATHERAPI_COLLECTOR_RUN_SCHEDULER:-true}
      DYNACONF_WEATHERAPI__SCHEDULER: ${WEATHERAPI_SCHEDULER_LIB:-apscheduler_lib}
      DYNACONF_WEATHERAPI__SAVE_TO_DB: ${WEATHERAPI_COLLECTOR_SAVE_TO_DB:-true}

      DYNACONF_DATABASE__DB_TYPE: ${WEATHERAPI_COLLECTOR_DB_TYPE:-sqlite}
      DYNACONF_DATABASE__DB_DRIVERNAME: ${WEATHERAPI_COLLECTOR_DB_DRIVERNAME:-sqlite+pysqlite}
      DYNACONF_DATABASE__DB_USERNAME: ${WEATHERAPI_COLLECTOR_DB_USERNAME}
      DYNACONF_DATABASE__DB_PASSWORD: ${WEATHERAPI_COLLECTOR_DB_PASSWORD}
      DYNACONF_DATABASE__DB_HOST: ${WEATHERAPI_COLLECTOR_DB_HOST}
      DYNACONF_DATABASE__DB_PORT: ${WEATHERAPI_COLLECTOR_DB_PORT}
      DYNACONF_DATABASE__DB_DATABASE: ${WEATHERAPI_COLLECTOR_DB_DATABASE:-/app/.db/weatherapi-collector.db}
      DYNACONF_DATABASE__DB_ECHO: ${WEATHERAPI_COLLECTOR_DB_ECHO:-false}
    volumes:
      - ../../shared/src:/app/shared/src:ro
      - ../../collectors/weatherapi-collector/src:/app/collectors/weatherapi-collector/src:ro
      - ${WEATHERAPI_COLLECTOR_LOGS_DIR:-weatherapi_collector_logs}:/var/log/weatherapi-collector
      - ${WEATHERAPI_COLLECTOR_DB_DIR:-weatherapi_collector_db}:/app/.db
