---
services:
  weatherapi-collector:
    restart: unless-stopped
    build:
      ## Set context to repo root
      context: ../..
      dockerfile: containers/weatherapi-collector/Dockerfile
    working_dir: /app
    container_name: weatherapi-collector
    command: ["python3", "-m", "weatherapi_collector"]
    environment:
      PYTHONPATH: /app/shared/src:/app/collectors/weatherapi-collector/src
      TZ: ${TZ:-Etc/UTC}

      DYNACONF_LOGGING__LOG_LEVEL: ${WEATHERAPI_COLLECTOR_LOG_LEVEL:-INFO}
      DYNACONF_LOGGING__LOG_FILE_PATH: ${WEATHERAPI_COLLECTOR_LOG_FILE_PATH:-/app/logs/weatherapi-collector.log}

      DYNACONF_HTTP__USE_CACHE: ${WEATHERAPI_COLLECTOR_USE_HTTP_CACHE:-false}
      DYNACONF_HTTP__CACHE_TYPE: ${WEATHERAPI_COLLECTOR_HTTP_CACHE_TYPE:-sqlite}
      DYNACONF_HTTP__CACHE_FILE_DIR: ${WEATHERAPI_COLLECTOR_HTTP_CACHE_DIR:-/app/.cache/http/hishel}
      DYNACONF_HTTP__CACHE_DB_FILE: ${WEATHERAPI_COLLECTOR_HTTP_CACHE_DB_FILE:-/app/.cache/weatherapi-collector/http/hishel.sqlite3}
      DYNACONF_HTTP__CACHE_CHECK_TTL_EVERY: ${WEATHERAPI_COLLECTOR_HTTP_CACHE_CHECK_TTL_EVERY:-60}
      DYNACONF_HTTP__CACHE_TTL: ${WEATHERAPI_COLLECTOR_HTTP_CACHE_TTL:-300}

      DYNACONF_WEATHERAPI__API_KEY: ${WEATHERAPI_KEY}
      DYNACONF_WEATHERAPI__LOCATION_NAME: ${WEATHERAPI_LOCATION_NAME}
      DYNACONF_WEATHERAPI__RUN_SCHEDULER: ${WEATHERAPI_COLLECTOR_RUN_SCHEDULER:-true}
      DYNACONF_WEATHERAPI__SAVE_TO_DB: ${WEATHERAPI_COLLECTOR_SAVE_TO_DB:-true}

      DYNACONF_DATABASE__DB_TYPE: ${WEATHERAPI_COLLECTOR_DB_TYPE:-sqlite}
      DYNACONF_DATABASE__DB_DRIVERNAME: ${WEATHERAPI_COLLECTOR_DB_DRIVERNAME:-sqlite+pysqlite}
      DYNACONF_DATABASE__DB_USERNAME: ${WEATHERAPI_COLLECTOR_DB_USERNAME}
      DYNACONF_DATABASE__DB_PASSWORD: ${WEATHERAPI_COLLECTOR_DB_PASSWORD}
      DYNACONF_DATABASE__DB_HOST: ${WEATHERAPI_COLLECTOR_DB_HOST}
      DYNACONF_DATABASE__DB_PORT: ${WEATHERAPI_COLLECTOR_DB_PORT}
      DYNACONF_DATABASE__DB_DATABASE: ${WEATHERAPI_COLLECTOR_DB_DATABASE}
      DYNACONF_DATABASE__DB_ECHO: ${WEATHERAPI_COLLECTOR_DB_ECHO:-false}
    volumes:
      - ../../shared/src:/app/shared/src:ro
      - ../../collectors/weatherapi-collector/src:/app/collectors/weatherapi-collector/src:ro
